### ISSUE TITLE
Submit project roadmap

### ISSUE THREAD

**Issue by hongchaodeng** [hongchaodeng/gitops-oam#1]
ref: https://github.com/oam-dev/spec/issues/362

Goal:
- submit a roadmap doc to doc/roadmap.md

The roadmap will cover:
- Project goal
    - includes end to end story from developer to k8s application deployments
- Thinking
    - Think about why we want to do this work? How it is useful to others?
- Actions
    - Includes weekly/bi-weekly plans to achieve the goal.
    - Compares Argo CD and Flux

**Comment by anubhavpulkit** [comment]
Done in #2
